name: Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Run Tests Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 19.x

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Run Test
        run: pnpm test:ci
